M48
; DRILL file {KiCad 7.0.8} date 2024 March 11, Monday 02:55:53
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-11T02:55:53-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.800
%
G90
G05
T1
X123.19Y-49.53
X123.19Y-90.17
X138.43Y-49.53
X138.43Y-90.17
T0
M30
