M48
; DRILL file {KiCad 7.0.8} date 2024 January 12, Friday 01:58:59
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-12T01:58:59-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X100.0Y-95.0
X112.0Y-83.0
T2
X125.38Y-77.14
X125.38Y-117.78
X140.62Y-77.14
X140.62Y-117.78
T0
M30
